name: CD - Deploy to AKS

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

  
    env:
      DEPLOY_ENV: production
      APP_URL: http://4.250.217.126
      REGISTRY: olaacr01.azurecr.io
      RESOURCE_GROUP: ola-rg
      CLUSTER_NAME: ola-aks
      NAMESPACE: default
      IMAGE_NAME: ola-portfolio-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download image tag from CI workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml       
          run_id: ${{ github.event.workflow_run.id }}
          name: image-tag
          path: .

      - name: Set IMAGE variable
        run: echo "IMAGE=$(cat image-tag.txt)" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

      - name: Update and apply manifest
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml -n $NAMESPACE

      - name: Monitor rollout
        run: |
          echo "Monitoring rollout..."
          if ! kubectl rollout status deployment/$IMAGE_NAME -n $NAMESPACE --timeout=3m; then
            echo "Rollout failed. Rolling back..."
            kubectl rollout undo deployment/$IMAGE_NAME -n $NAMESPACE
            exit 1
          else
            echo "Rollout successful!"
          fi

      - name: Verify Pod Health
        run: |
          echo "Verifying pod health..."
          kubectl get pods -n $NAMESPACE
          if [[ $(kubectl get pods -n $NAMESPACE -l app=$IMAGE_NAME -o jsonpath='{.items[*].status.containerStatuses[*].ready}') != *"true"* ]]; then
            echo "Some pods not ready!"
            kubectl describe pods -n $NAMESPACE
            exit 1
          else
            echo "All pods are healthy and running!"
          fi
